#!/bin/sh
# Copyright 2019 Tyler Listoe 
#
# Simply start all apps


/legato/systems/current/bin/app start imuLogger
/legato/systems/current/bin/app start gnssLogger
/legato/systems/current/bin/app start rfidTemp

